services:
  postgres:
    image: pgvector/pgvector:pg16

    container_name: incident-postgres

    restart: always

    environment:
      POSTGRES_DB: incident_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: incident-platform

    depends_on:
      - postgres

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/incident_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_AI_OLLAMA_BASE_URL: http://host.docker.internal:11434

volumes:
  postgres_data:
