server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incident_db?options=-c%20timezone=Asia/Kolkata
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

    locations: classpath:db/migration
